config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/index.html"), name="index"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("simulator.users.urls", namespace="users")),
    path("lotto/", include("simulator.lotto.urls", namespace="lotto")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

simulator/lotto/urls.py
from django.urls import path

from .views import (
    GenerateLottoCouponsView,
    LottoGameCreateView,
    LottoGameDeleteView,
    LottoGameDetailsView,
    LottoGameUpdateView,
    LottoHomePageView,
    RemoveCouponsView,
)

app_name = "lotto"

urlpatterns = [
    path("", view=LottoHomePageView.as_view(), name="index"),
    path("create/", view=LottoGameCreateView.as_view(), name="create"),
    path("<int:pk>/", view=LottoGameDetailsView.as_view(), name="details"),
    path("<int:pk>/update/", view=LottoGameUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", view=LottoGameDeleteView.as_view(), name="delete"),
    path("<int:pk>/clear/", view=RemoveCouponsView.as_view(), name="clear"),
    path("<int:pk>/random/", view=GenerateLottoCouponsView.as_view(), name="generate-coupons"),
]

simulator/users/urls.py
from django.urls import path

from simulator.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

simulator/lotto/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class AbstractGame(models.Model):
    STATUS_CHOICES = [
        ("OPEN", _("Open")),
        ("CLOSED", _("Closed")),
    ]

    date = models.DateField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="OPEN")
    objects = models.Manager()

    def __str__(self):
        return f"{self.__class__.__name__} {self.id} - {self.date} ({self.status})"

    class Meta:
        abstract = True


class LottoGame(AbstractGame):
    numbers = models.JSONField(blank=True, null=True)

    @property
    def user_coupons(self):
        return self.lottocoupons.count()

    class Meta:
        verbose_name = _("Lotto game")
        verbose_name_plural = _("Lotto games")
        ordering = ["-date"]


class LottoCoupon(models.Model):
    LOTTO_STATUSES = (
        ("6", "6"),
        ("5", "5"),
        ("4", "4"),
        ("3", "3"),
        ("2", "2"),
        ("1", "1"),
        ("0", "0"),
        ("OPEN", "Open"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="lottocoupons")
    game = models.ForeignKey(LottoGame, on_delete=models.CASCADE, related_name="lottocoupons")
    status = models.CharField(choices=LOTTO_STATUSES, default="OPEN", max_length=10)
    numbers = models.JSONField()

    objects = models.Manager()

    def __str__(self):
        return f"{self.user.username}'s Lotto numbers for Game id: {self.game_id}"

    class Meta:
        verbose_name = _("Lotto coupon")
        verbose_name_plural = _("Lotto coupons")

simulator/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for random_games_simulator.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

simulator/lotto/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from .models import LottoGame


class RandomLottoForm(forms.Form):
    quantity = forms.IntegerField(
        label="Number of coupons",
        min_value=1,
        max_value=1000000,
        initial=100000,
        help_text="Enter a quantity greater than 0 and smaller or equal to 1 000 000",
    )

    def clean_quantity(self):
        quantity = self.cleaned_data.get("quantity")

        if quantity is not None and (quantity < 1 or quantity > 1000000):
            raise forms.ValidationError("Quantity must be greater than 0 and smaller than 1 000 001")

        return quantity


class NewLottoGameForm(forms.ModelForm):
    date = forms.DateField(
        widget=forms.DateInput,
        label="Date of the lottery:",
        initial=timezone.now(),
        help_text="Enter a date which you would like to simulate",
    )

    class Meta:
        model = LottoGame
        fields = ("date",)


class LottoGameUpdateForm(NewLottoGameForm):
    n1 = forms.IntegerField(min_value=1, max_value=49, required=False, label="Number 1")
    n2 = forms.IntegerField(min_value=1, max_value=49, required=False, label="Number 2")
    n3 = forms.IntegerField(min_value=1, max_value=49, required=False, label="Number 3")
    n4 = forms.IntegerField(min_value=1, max_value=49, required=False, label="Number 4")
    n5 = forms.IntegerField(min_value=1, max_value=49, required=False, label="Number 5")
    n6 = forms.IntegerField(min_value=1, max_value=49, required=False, label="Number 6")

    class Meta:
        model = LottoGame
        fields = ("date", "n1", "n2", "n3", "n4", "n5", "n6")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.numbers:
            for i in range(6):
                field_name = f"n{i + 1}"
                self.fields[field_name] = forms.IntegerField(
                    min_value=1,
                    max_value=49,
                    required=False,
                    label=f"Number {i + 1}",
                    initial=self.instance.numbers[i],
                )

    def clean(self):
        cleaned_data = super().clean()
        n1 = cleaned_data.get("n1")
        n2 = cleaned_data.get("n2")
        n3 = cleaned_data.get("n3")
        n4 = cleaned_data.get("n4")
        n5 = cleaned_data.get("n5")
        n6 = cleaned_data.get("n6")

        numbers = [n1, n2, n3, n4, n5, n6]

        if any(numbers) and not all(numbers):
            raise ValidationError("All 6 numbers must be given")

        if all(numbers):
            if len(set(numbers)) != 6:
                raise ValidationError("All 6 numbers must be unique")

            self.cleaned_data["numbers"] = numbers

        return self.cleaned_data

simulator/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

simulator/lotto/views.py
import json

from celery import states
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Case, DecimalField, Value, When
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, FormView, ListView, RedirectView, TemplateView, UpdateView
from django_celery_results.models import TaskResult

from .forms import LottoGameUpdateForm, NewLottoGameForm, RandomLottoForm
from .models import LottoCoupon, LottoGame
from .tasks import bulk_create_coupons, bulk_update_coupons_status


class LottoHomePageView(LoginRequiredMixin, TemplateView):
    template_name = "pages/lotto_games.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        task_running = TaskResult.objects.filter(status=states.STARTED).first()
        games = LottoGame.objects.all()

        if task_running:
            task_data = json.loads(task_running.result)
            games = games.annotate(
                task_progress=Case(
                    When(id=task_data.get("game_id"), then=task_data.get("progress")),
                    default=Value(None),
                    output_field=DecimalField(),
                ),
            )

        open_games = games.filter(status="OPEN")
        context["open_games"] = open_games

        closed_games = games.filter(status="CLOSED")
        context["closed_games"] = closed_games

        return context


class LottoGameCreateView(LoginRequiredMixin, CreateView):
    template_name = "pages/form.html"
    model = LottoGame
    form_class = NewLottoGameForm
    success_url = reverse_lazy("lotto:index")
    extra_context = {"text": "Create new game"}


class LottoGameUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "pages/form.html"
    model = LottoGame
    form_class = LottoGameUpdateForm
    success_url = reverse_lazy("lotto:index")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["text"] = str(self.get_object()) + " - Update"
        context["coupons"] = self.object.lottocoupons.count()
        return context

    def form_valid(self, form):
        game = self.object

        if form.cleaned_data.get("numbers"):
            game.numbers = form.cleaned_data["numbers"]

        if game.numbers and len(game.numbers) == 6:
            game.status = "CLOSED"
            game.save()

            bulk_update_coupons_status.delay(game.id)  # perform coupons evaluation in the background (Celery)

        return super().form_valid(form)


class LottoGameDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "pages/form.html"
    model = LottoGame
    success_url = reverse_lazy("lotto:index")
    extra_context = {"text": "Are you sure to delete this game?", "btn_color": "btn-danger", "btn_name": "Delete"}


class LottoGameDetailsView(LoginRequiredMixin, ListView):
    template_name = "pages/lotto_game_details.html"
    context_object_name = "lotto_coupons"
    paginate_by = 100

    def get_queryset(self):
        pk = self.kwargs.get("pk")
        return LottoCoupon.objects.filter(game_id=pk, user=self.request.user).order_by("-status")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context["game"] = queryset.first().game
        context["total_coupons"] = queryset.count()
        context["chance"] = round((context["total_coupons"] / 13983816) * 100, 2)
        context["hit_6"] = queryset.filter(status="6").count()
        context["hit_6_prc"] = round((context["hit_6"] / context["total_coupons"]) * 100, 2)
        context["hit_6_prize"] = context["hit_6"] * 15000000
        context["hit_5"] = queryset.filter(status="5").count()
        context["hit_5_prc"] = round((context["hit_5"] / context["total_coupons"]) * 100, 2)
        context["hit_5_prize"] = context["hit_5"] * 5000
        context["hit_4"] = queryset.filter(status="4").count()
        context["hit_4_prc"] = round((context["hit_4"] / context["total_coupons"]) * 100, 2)
        context["hit_4_prize"] = context["hit_4"] * 100
        context["hit_3"] = queryset.filter(status="3").count()
        context["hit_3_prize"] = context["hit_3"] * 20
        context["hit_3_prc"] = round((context["hit_3"] / context["total_coupons"]) * 100, 2)
        context["hit_2"] = queryset.filter(status="2").count()
        context["hit_2_prc"] = round((context["hit_2"] / context["total_coupons"]) * 100, 2)
        context["hit_2_prize"] = 0
        context["hit_1"] = queryset.filter(status="1").count()
        context["hit_1_prc"] = round((context["hit_1"] / context["total_coupons"]) * 100, 2)
        context["hit_1_prize"] = 0
        context["hit_0"] = queryset.filter(status="0").count()
        context["hit_0_prc"] = round((context["hit_0"] / context["total_coupons"]) * 100, 2)
        context["hit_0_prize"] = 0
        context["total_prize"] = (
            context["hit_6_prize"] + context["hit_5_prize"] + context["hit_4_prize"] + context["hit_3_prize"]
        )

        paginator = Paginator(context["lotto_coupons"], self.paginate_by)

        page = self.request.GET.get("page", 1)

        try:
            lotto_coupons = paginator.page(page)
        except PageNotAnInteger:
            lotto_coupons = paginator.page(1)
        except EmptyPage:
            lotto_coupons = paginator.page(paginator.num_pages)

        context["lotto_coupons"] = lotto_coupons
        return context


class GenerateLottoCouponsView(LoginRequiredMixin, FormView):
    template_name = "pages/form.html"
    form_class = RandomLottoForm
    success_url = reverse_lazy("lotto:index")
    extra_context = {"text": "Add coupons"}

    def form_valid(self, form):
        game_id = self.kwargs["pk"]
        cleaned_data = form.cleaned_data
        quantity = cleaned_data["quantity"]

        bulk_create_coupons.delay(self.request.user.id, game_id, quantity)
        if quantity > 1000:
            messages.info(
                self.request,
                "Coupons are being generated in the background. Please wait until all coupons are generated",
            )
        return HttpResponseRedirect(self.get_success_url())


class RemoveCouponsView(RedirectView):
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        game_id = self.kwargs["pk"]
        LottoGame.objects.get(pk=game_id).lottocoupons.filter(user=self.request.user).delete()

        return reverse("lotto:index")

simulator/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

simulator/templates/pages/form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
  {% if text %}<h3 class="h3 my-3">{{ text }}</h3>{% endif %}
  {% if coupons %}
    <h5 class="h5 mt-3">
      Coupons in game: {{ coupons }}
    {% endif %}
  </h5>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit"
           class="btn {% if btn_color %}{{ btn_color }}{% else %}btn-primary{% endif %}"
           value="{% if btn_name %}{{ btn_name }}{% else %}Confirm{% endif %}" />
  </form>
{% endblock content %}

simulator/templates/pages/index.html
{% extends "base.html" %}

{% block content %}
  <style>
    .game-image {
      width: 200px
    }
  </style>
  <div class="container mt-5">
    <div class="row mx-auto">
      <!-- Game 1: Lotto -->
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="https://www.lotto.pl/cdn/f0adfd19562deeb4a89a1da2518a62fc.svg"
               class="card-img-top game-image"
               alt="Lotto Image" />
          <div class="card-body">
            <a href="{% url 'lotto:index' %}" class="btn btn-primary">Play Now</a>
          </div>
        </div>
      </div>
      <!-- Game 2: Eurojackpot -->
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="https://upload.wikimedia.org/wikipedia/en/a/a8/Eurojackpot_logo.png"
               class="card-img-top game-image"
               alt="Eurojackpot Image" />
          <div class="card-body">
            <a href="#" class="btn btn-primary disabled">Coming soon!</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

simulator/templates/pages/lotto_game_details.html
{% extends "base.html" %}

{% load humanize %}

{% block content %}
  <div class="container mt-3">
    <p>
      Lotto > <a class="no-text-decorations" href="{% url 'lotto:index' %}">Games</a> > {{ game }}
    </p>
    <div class="col col-lg-8 mx-auto">
      <div class="card mb-4 shadow-sm bg-light">
        <div class="card-body text-center">
          <h5 class="card-title mb-3">Game Information</h5>
          <p class="card-text">
            Game Date: <span class="fw-bold">{{ game.date }}</span>
          </p>
          <p class="card-text">
            Winning Numbers: <span class="text-primary fw-bold">{{ game.numbers }}</span>
          </p>
          <p class="card-text">
            Game Status: <span class="fw-bold">{{ game.status }}</span> <a class="link-danger" href="{% url 'lotto:update' pk=game.pk %}">(Change)</a>
          </p>
          <p class="card-text">
            Total Coupons: <span class="fw-bold">{{ total_coupons|intcomma }}</span> <a class="link-success"
    href="{% url 'lotto:generate-coupons' pk=game.pk %}">(Add)</a>
          </p>
          <p class="card-text">
            Chance of winning top prize: <span class="fw-bold">{{ chance }}%</span>
          </p>
        </div>
      </div>
      <div class="shadow-sm">
        <table class="table table-bordered table-sm align-middle text-center my-3">
          <thead>
            <tr class="text-center">
              <th class="col col-lg-3">Status</th>
              <th class="col col-lg-3">Hits</th>
              <th class="col col-lg-3">% of Hits</th>
              <th class="col col-lg-3">Value [PLN]</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Hit 6</td>
              <td>{{ hit_6 }}</td>
              <td>{{ hit_6_prc }}</td>
              <td>{{ hit_6_prize|intcomma }}</td>
            </tr>
            <tr>
              <td>Hit 5</td>
              <td>{{ hit_5|intcomma }}</td>
              <td>{{ hit_5_prc }}</td>
              <td>{{ hit_5_prize|intcomma }}</td>
            </tr>
            <tr>
              <td>Hit 4</td>
              <td>{{ hit_4|intcomma }}</td>
              <td>{{ hit_4_prc }}</td>
              <td>{{ hit_4_prize|intcomma }}</td>
            </tr>
            <tr>
              <td>Hit 3</td>
              <td>{{ hit_3|intcomma }}</td>
              <td>{{ hit_3_prc }}</td>
              <td>{{ hit_3_prize|intcomma }}</td>
            </tr>
            <tr>
              <td>Hit 2</td>
              <td>{{ hit_2|intcomma }}</td>
              <td>{{ hit_2_prc }}</td>
              <td>{{ hit_2_prize }}</td>
            </tr>
            <tr>
              <td>Hit 1</td>
              <td>{{ hit_1|intcomma }}</td>
              <td>{{ hit_1_prc }}</td>
              <td>{{ hit_1_prize }}</td>
            </tr>
            <tr>
              <td>Hit 0</td>
              <td>{{ hit_0|intcomma }}</td>
              <td>{{ hit_0_prc }}</td>
              <td>{{ hit_0_prize }}</td>
            </tr>
          </tbody>
          <tfoot>
            <tr>
              <td>Total</td>
              <td></td>
              <td></td>
              <td>{{ total_prize|intcomma }}</td>
            </tr>
          </tfoot>
        </table>
      </div>
      <table class="table table-sm table-borderless mt-3 text-center">
        <thead>
          <tr>
            <th class="col col-lg-2">Coupon id</th>
            <th class="col col-lg-4">Numbers</th>
            <th class="col col-lg-2">Status</th>
          </tr>
        </thead>
        <tbody>
          {% for coupon in lotto_coupons %}
            <tr>
              <td>{{ coupon.id }}</td>
              <td>{{ coupon.numbers }}</td>
              <td>{{ coupon.status }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% if lotto_coupons.has_other_pages %}
      <nav>
        <ul class="pagination justify-content-center mt-3">
          {% if lotto_coupons.has_previous %}
            <li class="page-item">
              <a class="page-link"
                 href="?page={{ lotto_coupons.previous_page_number }}">Previous</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Previous</span>
            </li>
          {% endif %}
          {% for i in lotto_coupons.paginator.page_range %}
            {% if lotto_coupons.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
          {% endfor %}
          {% if lotto_coupons.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ lotto_coupons.next_page_number }}">Next</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Next</span>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>
{% endblock content %}

simulator/templates/pages/lotto_games.html
{% extends "base.html" %}

{% load humanize %}

{% block content %}
  <div class="container mt-3">
    <a href="{% url 'lotto:create' %}" class="btn btn-primary btn-lg mb-4">Add new game</a>
    {% if open_games %}
      <div class="container rounded shadow-sm">
        <h4>Open games:</h4>
        <table class="table mb-5 align-middle">
          <thead>
            <tr>
              <th scope="col">Game</th>
              <th scope="col">Your Coupons</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            {% for game in open_games %}
              <tr>
                <td class="col col-lg-4">
                  {% if game.task_progress %}
                    <span class="text-primary">Work in progress ... {{ game.task_progress }}%</span>
                  {% else %}
                    <a href="{% url 'lotto:details' pk=game.pk %}"
                       class="link-primary link-offset-3 link-underline link-underline-opacity-25 link-underline-opacity-100-hover">
                      {{ game }}
                    </a>
                  {% endif %}
                </td>
                <td class="col col-lg-3">{{ game.user_coupons|intcomma }}</td>
                <td>
                  <a href="{% url 'lotto:generate-coupons' pk=game.pk %}"
                     class="btn btn-success btn-sm">Add Coupons</a>
                  <a href="{% url 'lotto:update' pk=game.pk %}"
                     class="btn btn-warning btn-sm">Update/Evaluate</a>
                  <a href="{% url 'lotto:delete' pk=game.pk %}"
                     class="btn btn-danger btn-sm">Delete</a>
                  <a href="{% url 'lotto:clear' pk=game.pk %}" class="btn btn-dark btn-sm">Remove coupons</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% endif %}
    {% if closed_games %}
      <div class="container rounded shadow-sm">
        <h4>Closed games:</h4>
        <table class="table align-middle">
          <thead>
            <tr>
              <th scope="col">Game</th>
              <th scope="col">Your Coupons</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            {% for game in closed_games %}
              <tr>
                <td class="col col-lg-4">
                  {% if game.task_progress %}
                    <span class="text-success">Work in progress ... {{ game.task_progress }}%</span>
                  {% else %}
                    <a href="{% url 'lotto:details' pk=game.pk %}"
                       class="link-secondary link-offset-3 link-underline link-underline-opacity-25 link-underline-opacity-100-hover">
                      {{ game }}
                    </a>
                  {% endif %}
                </td>
                <td class="col col-lg-3">{{ game.user_coupons|intcomma }}</td>
                <td>
                  <a href="{% url 'lotto:generate-coupons' pk=game.pk %}"
                     class="btn btn-success btn-sm">Add Coupons</a>
                  <a href="{% url 'lotto:update' pk=game.pk %}"
                     class="btn btn-warning btn-sm">Update/Evaluate</a>
                  <a href="{% url 'lotto:delete' pk=game.pk %}"
                     class="btn btn-danger btn-sm">Delete</a>
                  <a href="{% url 'lotto:clear' pk=game.pk %}" class="btn btn-dark btn-sm">Remove coupons</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% endif %}
  </div>
{% endblock content %}